### ISSUE TITLE
Add ability to include Google analytics scripts in history and search pages

### ISSUE THREAD

**Issue by ElliotSilver** [HL7/fhir-ig-history-template#2]
This is a follow-on from HL7/ig-template-base#256.

The same script needs to be added to the history and search pages used when running in -go-publish mode (defined in https://github.com/HL7/fhir-ig-history-template), with an ability to specify the tracker id. This may be the same solution as used in HL7/ig-template-base#256 or may need a different approach.

**Comment by lmckenzi** [comment]
Benefit is low and it's harder to pass in a parameter here than it is within an IG.  Given that combination, we're going to decline until someone comes forward with a strong use-case.
